
// PUBLIC KEY (Ed25519) - Generated by tools/generate_license_ed25519.js
const PUBLIC_KEY_BASE64 = "MCowBQYDK2VwAyEAhmnKXZ9uGGjPFIZ7wzHuLo6PiIJQb0EbxjXJEtC+o6M=";

function base64ToArrayBuffer(base64: string): ArrayBuffer {
    const binary_string = window.atob(base64);
    const len = binary_string.length;
    const bytes = new Uint8Array(len);
    for (let i = 0; i < len; i++) {
        bytes[i] = binary_string.charCodeAt(i);
    }
    return bytes.buffer;
}

function hexToUint8Array(hex: string): Uint8Array {
    if (hex.length % 2 !== 0) throw new Error('Invalid hex string');
    const array = new Uint8Array(hex.length / 2);
    for (let i = 0; i < hex.length; i += 2) {
        array[i / 2] = parseInt(hex.substr(i, 2), 16);
    }
    return array;
}

let cachedKey: CryptoKey | null = null;

async function getPublicKey(): Promise<CryptoKey> {
    if (cachedKey) return cachedKey;

    const keyBuffer = base64ToArrayBuffer(PUBLIC_KEY_BASE64);
    cachedKey = await window.crypto.subtle.importKey(
        "spki",
        keyBuffer,
        {
            name: "Ed25519",
        },
        true,
        ["verify"]
    );
    return cachedKey;
}

export async function verifyLicenseSignature(content: any, signatureHex: string): Promise<boolean> {
    try {
        const key = await getPublicKey();
        const signature = hexToUint8Array(signatureHex);
        
        // Canonicalize content the same way the signer did (JSON.stringify)
        // Note: Ideally we'd sign a hash or a stable serialization, but for this simple use case,
        // we rely on JSON.stringify behaving mostly consistently for simple objects, 
        // OR the generator ensures it matches.
        // The generator uses: JSON.stringify(payload)
        const data = new TextEncoder().encode(JSON.stringify(content));

        const isValid = await window.crypto.subtle.verify(
            {
                name: "Ed25519",
            },
            key,
            signature as any,
            data
        );

        return isValid;
    } catch (e) {
        console.error("Signature verification error:", e);
        return false;
    }
}
